/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SubmitFormImport } from './routes/submit-form'
import { Route as PreviewImport } from './routes/preview'
import { Route as CreateFormImport } from './routes/create-form'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const SubmitFormRoute = SubmitFormImport.update({
  id: '/submit-form',
  path: '/submit-form',
  getParentRoute: () => rootRoute,
} as any)

const PreviewRoute = PreviewImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => rootRoute,
} as any)

const CreateFormRoute = CreateFormImport.update({
  id: '/create-form',
  path: '/create-form',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/create-form': {
      id: '/create-form'
      path: '/create-form'
      fullPath: '/create-form'
      preLoaderRoute: typeof CreateFormImport
      parentRoute: typeof rootRoute
    }
    '/preview': {
      id: '/preview'
      path: '/preview'
      fullPath: '/preview'
      preLoaderRoute: typeof PreviewImport
      parentRoute: typeof rootRoute
    }
    '/submit-form': {
      id: '/submit-form'
      path: '/submit-form'
      fullPath: '/submit-form'
      preLoaderRoute: typeof SubmitFormImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create-form': typeof CreateFormRoute
  '/preview': typeof PreviewRoute
  '/submit-form': typeof SubmitFormRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create-form': typeof CreateFormRoute
  '/preview': typeof PreviewRoute
  '/submit-form': typeof SubmitFormRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/create-form': typeof CreateFormRoute
  '/preview': typeof PreviewRoute
  '/submit-form': typeof SubmitFormRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/create-form' | '/preview' | '/submit-form'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/create-form' | '/preview' | '/submit-form'
  id: '__root__' | '/' | '/create-form' | '/preview' | '/submit-form'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateFormRoute: typeof CreateFormRoute
  PreviewRoute: typeof PreviewRoute
  SubmitFormRoute: typeof SubmitFormRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateFormRoute: CreateFormRoute,
  PreviewRoute: PreviewRoute,
  SubmitFormRoute: SubmitFormRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/create-form",
        "/preview",
        "/submit-form"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/create-form": {
      "filePath": "create-form.tsx"
    },
    "/preview": {
      "filePath": "preview.tsx"
    },
    "/submit-form": {
      "filePath": "submit-form.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
